<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-13 06:49
=======
# Generated by Django 5.0.3 on 2024-04-12 23:28
>>>>>>> b82a137 (update payment)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_bool", models.BooleanField(default=False)),
                ("stripe_checkout_id", models.CharField(max_length=500)),
            ],
        ),
    ]
