<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-13 06:49
=======
# Generated by Django 5.0.3 on 2024-04-12 23:28
>>>>>>> b82a137 (update payment)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Shipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"is_superuser": 0},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
