# Generated by Django 5.0.3 on 2024-03-31 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Shipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
