# Generated by Django 5.0.3 on 2024-04-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Shipment", "0002_shipment_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shipment",
            options={"verbose_name": "Shipment", "verbose_name_plural": "Shipments"},
        ),
    ]
