# Generated by Django 5.0.3 on 2024-03-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0005_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
    ]
