# Generated by Django 5.0.3 on 2024-03-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='cart_id',
            field=models.IntegerField(default=0),
        ),
    ]
