# Generated by Django 5.0.3 on 2024-04-04 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_customer_id_alter_cart_item_product_id_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="cart_id",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="cart_item",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="cart_item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
