# Generated by Django 5.0.3 on 2024-04-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_remove_wishlist_cart_id_wishlist_product_id_and_more"),
    ]

    operations = []
