# Generated by Django 5.0.3 on 2024-04-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_auto_20240404_1356"),
    ]

    operations = []
