# Generated by Django 5.0.3 on 2024-04-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_wishlist_product_id"),
    ]

    operations = []
