# Generated by Django 5.0.3 on 2024-04-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = []
