# Generated by Django 5.0.3 on 2024-04-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "OrderItem", "verbose_name_plural": "OrderItem"},
        ),
    ]
