# Generated by Django 5.0.3 on 2024-04-01 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_creation_date",
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
