<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-04-12 20:20
=======
# Generated by Django 5.0.3 on 2024-04-12 04:40
>>>>>>> origin

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Order", "0001_initial"),
<<<<<<< HEAD
        ("Shipment", "0001_initial"),
=======
        ("products", "0001_initial"),
>>>>>>> origin
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="order",
            name="shipment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Shipment.shipment"
=======
            model_name="orderitem",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
>>>>>>> origin
            ),
        ),
    ]
