# Generated by Django 5.0.3 on 2024-04-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Order", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="product",
            new_name="product_id",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
