# Generated by Django 5.0.3 on 2024-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="rating",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
