# Generated by Django 5.0.3 on 2024-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
