# Generated by Django 5.0.3 on 2024-04-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_stripe_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stripe_product",
        ),
        migrations.AddField(
            model_name="product",
            name="stripe_name",
            field=models.CharField(default="NoName", max_length=300),
        ),
    ]
