# Generated by Django 5.0.3 on 2024-04-12 03:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
